import { Product, Farmer } from './types';

export const INITIAL_FARMERS: Farmer[] = [
  {
    id: 'f1',
    name: 'Farmer Elias',
    farmName: 'Hillside Farm',
    location: 'Hillside Foothills',
    story: 'Elias grows our famous heirloom tomatoes, deep red sweet melons, and fresh herbs utilizing high-altitude organic practices and crystal-clear spring water.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 4.9,
    joinedDate: 'Joined May 2022'
  },
  {
    id: 'f2',
    name: 'Farmer Thomas Wayne',
    farmName: 'Green Valley Farm',
    location: 'Green Valley',
    story: 'Our family has been farming the Green Valley for three generations. We use regenerative practices that prioritize soil health and absolute freshness. When you buy our chard, it was in the ground just six hours ago.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpScf4Db8psdWxsPx5TMFNZng2V4Om5bZzHvwRNP6g6g3_IgSPi4mmOdzedVAvDmnaFmQOzm2WfM3xlrxOsRunp6qmT-RLXJneD_r0v0vsb0UB1s0QD9-o5m1tq_Q33vTKVcaNK3P7L6gb_97EXeSeMw0Cb2vaxTISqgWmKacFjlNbMIv9Lr2T17vMVjHawgugqAvkbHafUdyh6yi8GA2XVVByHX2tfiUqt2DIncoRAKzVgUYpdTNIovAJMMBv79P3upVwSlYS1nr0',
    rating: 5.0,
    joinedDate: 'Joined Sep 2021'
  },
  {
    id: 'f3',
    name: 'Farmer Sarah',
    farmName: 'Sarah’s Organic Patch',
    location: '2 mi away',
    story: 'Sarah operates a local community-supported garden specializing in high-nutrition root crops, multi-color organic carrots, and fresh-leaf greens.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    rating: 4.8,
    joinedDate: 'Joined Sep 2023'
  },
  {
    id: 'f4',
    name: 'Oak Creek Sustainable Farm',
    farmName: 'Oak Creek Sustainable Farm',
    location: 'Oak Creek Valley',
    story: 'Our family operates bountiful slope orchards and sustainable tomato patches. Our heirloom-only, soil-grown crops are picked at the peak of ripeness for the highest lycopene and incredible flavor.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6nSU4sq8hmsFvwnnYXr6yzZTDHnZKqSji87pbsUuvbJQ8RIgAieoE7NmYVucC0yten_xbbjHA06KB17EiiSqeoXdaWflPptqt82Sz3vyORDTjg3aJTCfSnOUwrXbjfZqUDRq9hGinea_1hQ0TPh7untNs33inClyv76UpAls742xIDRJ2wJOvQnPwIstcjCOVymzLRHTQrsdrDHYXIyc9hyPFkDKVQcsKy_Kw06sIjwq7PXaVvKTLH1zW7ojZF2zYSAzg_B_MnjlG',
    rating: 4.9,
    joinedDate: 'Joined Jun 2022'
  },
  {
    id: 'f5',
    name: 'Farmer Rajeev',
    farmName: 'Vedic Organic Acres',
    location: 'Deccan Highlands',
    story: 'Rajeev specializes in ancient Indian grains, heirloom organic vegetables, and heritage millets. He uses Vedic natural farming techniques, utilizing microbial humic soils to grow premium nutrients.',
    avatar: 'https://images.unsplash.com/photo-1542013936693-8848e574047e?auto=format&fit=crop&w=150&q=80',
    rating: 4.95,
    joinedDate: 'Joined Oct 2022'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Heirloom Mix',
    price: 4.50,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSMeEXBBt9mgmSHX8O1sTjdkhSkYXs0CacqUAvnGiFiCo-FeEvqaGnwLk3OQeKk_RrURU7TKmthFRThaywddWjo4mB-7iPgFejoXg3RFawBNkBxV6ionGbMC-rgR5Dqe-YT9HCaw2VzRyeMmhgt2bbn9Rjd9bW9Ouyq7pblUgBNRPljNjLO1d1DPiVLaGPJg7Kh_X0eVljdVI5X0PGBAC0jmazCikAdCn5JT-m1aC0cjnD4-BYiwayVyvUDJr_wmkx_7vi01iEO5hw',
    description: 'Vibrant, multi-colored heirloom tomatoes in shades of ruby red, deep orange, and sun-kissed yellow. Grown using high-altitude organic practices.',
    farmerId: 'f1',
    farmerName: 'Maplewood Organics',
    stock: 45,
    isOrganic: true
  },
  {
    id: 'p2',
    name: 'Vine Tomatoes',
    price: 3.25,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWSCGi1PJvU4IEGh9qdQUn7CF9y1Sp0_83MqLupCcDEIdotlKjY7cIXy7Clpl5TFTJA74ZeHSFWqi65s8BGZehXyXr3cS7aLrSR0pOycAWsKn2YFA_CUXDyI-VkARySCc8jpAi8YZ7zyXFJsQTM-MjBcl5MRcs2RV7NHQ26lXAGWPH4GE4qjkgx3RGsAVj8aHZ808zGp4J-5tnnTKSbVFkq1cAeXgfjTXhJxG4agSErzNCZxOB7VGM263s_sCctE_CpG6_xIHawoit',
    description: 'Bright red vine-ripened tomatoes still attached to their fresh green stems, arranged elegantly in a minimalist ceramic bowl.',
    farmerId: 'f2',
    farmerName: 'Green Valley Farm',
    stock: 22,
    isOrganic: false
  },
  {
    id: 'p3',
    name: 'Sun Gold Cherry',
    price: 5.00,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDqc19Ox2zU8DFN1C2RtWYX6q4ufqb8M9gP4ipZ97XrSD0FbDnxJrehBXn0wbmkLbEUkqoMeRgDhmDuNzM-tr5mKU0yb2Vil_5YSGOWvCTwXm_I5CasGbzF8Aljl4BuSMdiRbyeJZUMz3_XlVvsRGKZPM1xGZpRtkMdi7HGT06bQhRFp8xeapx5fLLmP2p0jjx8T4ZYB26O8TSCzRnZPL1shD-IcrpuNxTb4RXj51Wm8rjiSrv-eWXqG610_SOr13zhkuhW7CwK-YX0',
    description: 'Vivid, sugary sweet cherry tomatoes. Absolute premium crop grown in rich compost soil.',
    farmerId: 'f3',
    farmerName: 'Sunrise Acres',
    stock: 25,
    isOrganic: true
  },
  {
    id: 'p4',
    name: 'Big Beefsteaks',
    price: 2.80,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpdAE-fZ0OexfeNVtEj9hW2iPJMNKCur-TTUT-d_atQF2GikR4JpCMbQkAluNBTRjNO-Qm7Rsdu4h0l5umW9w_jcfy9dZT-juCz63BCTLP3TDlFvywzQeLRAEUaeFQ7QW8XWRZoj4kxxU6TFkiluz932LPXvlsS7Jx6FeTa3b8BkuGmA4nyy6aa1NKHTY9Y2MoJKtSA6DV20un7T6UyES6Hc8wroGmKJP9OMvOvCPb1OeTkJ9jofXYklB8WrcSsBcSmdCt56xqgT6w',
    description: 'Large, meaty beefsteak tomatoes with deep ridges and rich crimson color. Harvested during the golden hour.',
    farmerId: 'f4',
    farmerName: 'Old Oak Farmstead',
    stock: 50,
    isOrganic: false
  },
  {
    id: 'p5',
    name: 'Plum Roma',
    price: 1.95,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC1dmvj0DG6N-Xb2WnYYiI_VCpKqijSdyBcQ3dzoAHtcR3euP_K7J8j5Rzy4ltXZ1KqAytHCPo3iN37nMff0um6ONvhuGWc0Ip8M23CnwgEYSxOPKfR-3MNefnzAEZkQJQth7RpyswXCJOo3ZnRjF0IddSyy6dLtx2NmDfcbpV8U6XO3wK33rvOoOUcYA69C18k9F2whgGViXoZCXaZPujaMtp2hEmm0EwutfHWVSjFmOKsoUuDL8AC72iPRt9LS_VMkWCGZRFJK5q2',
    description: 'Oval-shaped Roma tomatoes. Minimalist and kitchen-ready, perfect for making rich organic sauces.',
    farmerId: 'f1',
    farmerName: 'Hillside Garden',
    stock: 30,
    isOrganic: false
  },
  {
    id: 'p6',
    name: 'Firm Green Tomatoes',
    price: 3.10,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBU6IBKdKFWMQgb9805HpenPknpcwod2sOw-Q1Jc9j3e4f_KhGmO9tkgbDFGa0-XMLxUEdaCQtUcHrn3s8YDh_0jvcZiQr14eziaeLrnbERLd6B5nBWvrtKzYblRCWiCuwn0dSOTKDc0xNJq3uvx4nZ2h9gFHbkSRpR54LeW2D9p1kPHfTervOopCzXe0kHA7E2hyNemCh3esOBfrr2RdF01_Xzcffw0rlYwbj0QrBvgZzYTVljjKgix2-bdCbw6g9cIl_iKBMw_awX',
    description: 'Firm, unripe green tomatoes in various sizes, arranged on a rustic linen fabric. Perfect for traditional Southern recipes.',
    farmerId: 'f2',
    farmerName: 'The Green Patch',
    stock: 18,
    isOrganic: false
  },
  {
    id: 'p7',
    name: 'Yellow Teardrops',
    price: 4.75,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8t4k4sYelSPYQydho2H1VAK8z4Dp67CzZgQqU_tkduC-yrMCKR94Nx5zLUfAqPaOHG57vYTkJc-qCuQYhVh3_vmhMxX2OK2aOIiu6iIFkAeDIDchM47fCWpHpXReofSvnqfM259SN-5g2GtTaSAO6_VpGJWkvRy6yV4h-0g7-S31aZ5jpe2aFvNHzXjuEw2vOZ8lorZK-4F9cn9AniWUPKLeoICTzkpVYbYL6ssNKYZ7RprckyvPL_zhWvIkUaFHReSBS0tVLqb4o',
    description: 'Petite, pear-shaped yellow tomatoes glowing with a bright, sunny lemon hue. Extremely sweet flavor.',
    farmerId: 'f3',
    farmerName: 'Beehive Meadows',
    stock: 15,
    isOrganic: true
  },
  {
    id: 'p8',
    name: 'Black Krim Specials',
    price: 5.50,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBA3H19yFuJwOfq0pxXPdlTv3IUr3LtkcxY7HnjPgLOvAe9QONTxmAIugl23wFbTDTvZTGZLf26SgavH_SvAk77h0tJhxV5cdfV220lNN2d_o1hTkBoyx5FXXadM2ywd9_nDVnUVs6ArrBdOAV-QjYoexm1aS5azt0c0srJy4UA_-vzfq6vdCmZHAzMtp3p3Zba8Wb1sK1c3o_4X-GZerLpq7saGxPbfFCTmKVmOqaX4v3Bz3NwclaMpIWuI12kqFyi7c4YmOI42Ae6',
    description: 'Exotic Black Krim tomatoes with deep maroon and dark green skins. Highly rated for their complex, salty-sweet flavour profile.',
    farmerId: 'f4',
    farmerName: 'Indigo Heritage Farm',
    stock: 12,
    isOrganic: true
  },
  {
    id: 'p9',
    name: 'Rainier Cherries',
    price: 6.99,
    unit: 'lb',
    category: 'Fruits',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCefKltGIjU6fNQOaAY5DgqzbSdakSj1ymrBb8A5KoBS2c_VIRQcecbydtYwBGXrayXXlkbXwNbxfoG7oxJg7_koY9JYKfTHlXus1eiRB-H2eQ4b2p30_co9gQkF74hpOCs2TFSar3kJ94og-pj_ZM1WxACP6sNQaLdEYM0isO4WUb0PMl-l7gUBnFFo1oenJ1kDxmQh1cBR-NMGdGCoek72ayhHeTQW8l4W4rZBZS8uFGkqoU7-51J4uGU4HqWs9mnhaBRA-1xCuNJ',
    description: 'Glossy dark-red sweet Rainier cherries. Tender, ultra-sweet flesh picked fresh this morning.',
    farmerId: 'f4',
    farmerName: 'Oak Creek Orchards',
    stock: 30,
    isOrganic: false
  },
  {
    id: 'p10',
    name: 'Wildflower Honey',
    price: 14.00,
    unit: 'jar',
    category: 'Fruits',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqW2RNMEq-KutOup8hHmztGVtEEd4uDKwUAosv8tCSF8QDv6kKtoawhIC4N0NdB0ZgkrIgBzR7KtTnq1T23ej91-lQCPNUu1cYQ_8nQHHWtcikzNBQPAq2dSdImarhTUOn5SA2dtXXlO8yUjYYA0pQDS43BvYD2c-YGNz6pt9aHn3aZlDZClTEshTuEqwkQcz1uW3HEmCOPe4nIqwVPwC6-OGKxH-MYM44-DsIazUiQ5BgHf6Sa6daqEXU26vesj7xIH-q3DxtNNSF',
    description: 'Golden honeycomb and natural wildflower jar. Raw, unheated nectar rich in enzymes.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 18,
    isOrganic: true
  },
  {
    id: 'p11',
    name: 'Super Greens Bundle',
    price: 12.00,
    unit: 'bundle',
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3m-ADQpYlQVh9rPFkYoNNTfxZkZPu20B06YXIurFCnyDXrTTqovmmMqQoIohSgs_t_WoY-XY8H6kTOAJy2sOKAr9Jm7bFjCqfNkBGGtm6wwdv-lLxVySDi2JZVi-3hsBae270e7Cej5R8wy8S65T4NhO93G2leqCNcm1xgc9x4H0W75Jex_s0ydF6S3KxpG1z1-wT3212moIrnkmDPg2TCjYca_ZASGEw3Maj0rcNaJTygQgOhqyPv5YfX9zB4ncZHCt4UH7T817u',
    description: 'Crisp green kale and dark spinach harvested at sunrise.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 15,
    isOrganic: true
  },
  {
    id: 'p12',
    name: 'Artisanal Sourdough Loaf',
    price: 6.50,
    unit: 'loaf',
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=350&q=80',
    description: 'Crispy, thick crust with a light and airy interior. Naturally leavened sourdough bread baked daily.',
    farmerId: 'f1',
    farmerName: 'Hillside Farm',
    stock: 12,
    isOrganic: true
  },
  {
    id: 'p13',
    name: 'French Butter Croissants',
    price: 4.50,
    unit: '2-pack',
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=350&q=80',
    description: 'Golden-brown, flaky, buttery puff pastry freshly rolled and baked to perfection.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 20,
    isOrganic: false
  },
  {
    id: 'p14',
    name: 'Pastured Organic Eggs',
    price: 7.50,
    unit: 'dozen',
    category: 'Organic Eggs',
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=350&q=80',
    description: 'True pasture-raised chicken eggs with vibrant deep orange yolks. Nutrient-dense and high-grade organic.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 30,
    isOrganic: true
  },
  {
    id: 'p15',
    name: 'Duck Eggs Pasture-Raised',
    price: 9.50,
    unit: '6-pack',
    category: 'Organic Eggs',
    image: 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?auto=format&fit=crop&w=350&q=80',
    description: 'Extra creamy duck eggs raised entirely on free pasture. Excellent for gourmet baking and rich omelets.',
    farmerId: 'f3',
    farmerName: 'Sarah’s Organic Patch',
    stock: 10,
    isOrganic: true
  },
  {
    id: 'p16',
    name: 'Fresh Grass-Fed Butter',
    price: 5.80,
    unit: 'block',
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=350&q=80',
    description: 'Churned from pure grass-fed cream. Deep golden yellow and exceptionally smooth and flavorful.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 25,
    isOrganic: true
  },
  {
    id: 'p17',
    name: 'Artisan Goat Milk Cheese',
    price: 8.50,
    unit: 'oz',
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1486299267070-8382e214434b?auto=format&fit=crop&w=350&q=80',
    description: 'Mild, tangy, and spreadable soft chèvre cheese handcrafted by Sarah from certified grass-fed goats.',
    farmerId: 'f3',
    farmerName: 'Sarah’s Organic Patch',
    stock: 15,
    isOrganic: true
  },
  {
    id: 'p18',
    name: 'Organic Whole Milk',
    price: 4.80,
    unit: 'half-gal',
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=350&q=80',
    description: 'Nutritious whole cream pasteurized organic milk from free-range pasture grazing cows.',
    farmerId: 'f1',
    farmerName: 'Hillside Farm',
    stock: 40,
    isOrganic: true
  },
  {
    id: 'p19',
    name: 'Fresh Organic Strawberries',
    price: 4.99,
    unit: 'basket',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1518635017498-87f514b751ba?auto=format&fit=crop&w=350&q=80',
    description: 'Sweet, juicy strawberries picked at optimal sugar levels from Sarah’s sun-drenched patch.',
    farmerId: 'f3',
    farmerName: 'Sarah’s Organic Patch',
    stock: 25,
    isOrganic: true
  },
  {
    id: 'p20',
    name: 'Honeycrisp Apples',
    price: 3.50,
    unit: 'lb',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1570913149827-d2ac223ed3e0?auto=format&fit=crop&w=350&q=80',
    description: 'Extra crisp and sweet Honeycrisp apples with a perfect balanced tang from Oak Creek Orchards.',
    farmerId: 'f4',
    farmerName: 'Oak Creek Sustainable Farm',
    stock: 40,
    isOrganic: false
  },
  {
    id: 'p21',
    name: 'Organic Blueberries',
    price: 5.50,
    unit: 'pint',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=350&q=80',
    description: 'Plump, antioxidant-rich dark blueberries freshly harvested during the early dawn dew.',
    farmerId: 'f3',
    farmerName: 'Sarah’s Organic Patch',
    stock: 20,
    isOrganic: true
  },
  {
    id: 'p22',
    name: 'Sweet Elberta Peaches',
    price: 4.80,
    unit: 'lb',
    category: 'Fruits',
    image: 'https://images.unsplash.com/photo-1541256996761-85df2efaa164?auto=format&fit=crop&w=350&q=80',
    description: 'Fleshy, aromatic golden yellow peaches with beautiful red blushes, incredibly juicy.',
    farmerId: 'f2',
    farmerName: 'Farmer Thomas Wayne',
    stock: 15,
    isOrganic: true
  },
  {
    id: 'p23',
    name: 'Bhindi (Organic Okra)',
    price: 2.40,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1625940484082-8bc049f3e496?auto=format&fit=crop&w=350&q=80',
    description: 'Fresh, tender green Okra (Bhindi). Crunchy, nutrient-dense, and highly versatile for traditional stir-fries or crisp bhindi masala.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 35,
    isOrganic: true
  },
  {
    id: 'p24',
    name: 'Baingan (Indian Eggplant / Brinjal)',
    price: 1.99,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1590371391694-06788db3d721?auto=format&fit=crop&w=350&q=80',
    description: 'Glossy, dark-purple Indian teardrop brinjal (Baingan). Tender, meaty flesh, perfect for roasting, stuffing, or making classic bharta.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 40,
    isOrganic: true
  },
  {
    id: 'p25',
    name: 'Aloo (Regenerative Potatoes)',
    price: 1.50,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=350&q=80',
    description: 'Freshly dug organic yellow potatoes (Aloo). Rich earthy skin with an ultra-creamy, high-starch texture.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 100,
    isOrganic: true
  },
  {
    id: 'p26',
    name: 'Gobi (Heirloom Cauliflower)',
    price: 2.99,
    unit: 'head',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1568584711271-6c929fb49b60?auto=format&fit=crop&w=350&q=80',
    description: 'Tight, ivory-white cauliflower curds framed by crisp, protective green-rib leaves. Rich in minerals and vitamin C.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 25,
    isOrganic: true
  },
  {
    id: 'p27',
    name: 'Patta Gobi (Crisp Green Cabbage)',
    price: 1.80,
    unit: 'head',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1598170845058-32b996a6bd37?auto=format&fit=crop&w=350&q=80',
    description: 'Tightly packed, crisp green heads of traditional cabbage with sweet, sweet, juicy inner layers.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 30,
    isOrganic: true
  },
  {
    id: 'p28',
    name: 'Pyaz (Red Slicing Onions)',
    price: 1.60,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1508747703725-719ae257c14a?auto=format&fit=crop&w=350&q=80',
    description: 'Pungent, crispy, high-flavor red onions (Pyaz). Hand-harvested, cured on dry racks, and packed with traditional sweetness.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 80,
    isOrganic: true
  },
  {
    id: 'p29',
    name: 'Lahsun (Ancient Garlic Bulbs)',
    price: 3.50,
    unit: 'bundle',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=350&q=80',
    description: 'Robust heritage garlic cloves (Lahsun) with incredibly intense garlicky oil and strong medicinal compounds.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 30,
    isOrganic: true
  },
  {
    id: 'p30',
    name: 'Adrak (Polished Yellow Ginger)',
    price: 4.00,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=350&q=80',
    description: 'Zesty, high-gingerol spicy ginger roots (Adrak). Harvested fresh, perfect for spice pastes, curries, and herbal chai.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 25,
    isOrganic: true
  },
  {
    id: 'p31',
    name: 'Hari Mirch (Hot Green Chillies)',
    price: 2.20,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=350&q=80',
    description: 'Slender, hot green chillies (Hari Mirch) with brilliant fiery heat. Extends a punchy kick to authentic Indian curries.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 40,
    isOrganic: true
  },
  {
    id: 'p32',
    name: 'Kheera (Crisp Indian Cucumbers)',
    price: 1.85,
    unit: 'lb',
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1604975545595-653609804e87?auto=format&fit=crop&w=350&q=80',
    description: 'Crispy, hydrating, thinly-seeded cucumbers (Kheera). Delivers a beautiful cooling crunch to summer salads.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 50,
    isOrganic: true
  },
  {
    id: 'p33',
    name: 'Premium Basmati Rice (Aged)',
    price: 5.99,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=350&q=80',
    description: 'Extra-long grain premium aromatic Basmati rice. Aged for 12 months for fluffiness, fragrant rice kernels, and superior non-sticky texture.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 60,
    isOrganic: true
  },
  {
    id: 'p34',
    name: 'Heritage Pearl Millet (Bajra)',
    price: 3.50,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1574325131876-a7999788d8f0?auto=format&fit=crop&w=350&q=80',
    description: 'Iron-rich organic Pearl Millet (Bajra) grains. A high-energy ancient grain ideal for making traditional flatbreads (Bajra Roti).',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 45,
    isOrganic: true
  },
  {
    id: 'p35',
    name: 'Whole Finger Millet (Ragi / Nachni)',
    price: 3.80,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1597528147322-11342cb23f79?auto=format&fit=crop&w=350&q=80',
    description: 'Calcium-rich whole Finger Millet (Ragi / Nachni) seeds. Premium quality, organic, superfood grain for child nutrition porridge and healthy rotis.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 55,
    isOrganic: true
  },
  {
    id: 'p36',
    name: 'Unpolished Foxtail Millet',
    price: 4.20,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=350&q=80',
    description: 'Slow-digesting gluten-free Foxtail millet. Packed with dietary fibers and B vitamins, a perfect healthy substitute for standard table rice.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 30,
    isOrganic: true
  },
  {
    id: 'p37',
    name: 'Vedic Sorghum Grains (Jowar)',
    price: 3.40,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1574325131876-a7999788d8f0?auto=format&fit=crop&w=350&q=80',
    description: '100% natural organic White Sorghum (Jowar) grains. Loaded with antioxidants, protein, and dietary fiber. Ideal for healthy rotis and baking.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 40,
    isOrganic: true
  },
  {
    id: 'p38',
    name: 'Organic Sonamasuri Rice',
    price: 4.50,
    unit: '2lb bag',
    category: 'Grains & Millets',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=350&q=80',
    description: 'Premium medium-grain unpolished Sonamasuri raw rice. Mild sweet flavor, highly digestible, and grown using natural regenerative soil fertilizers.',
    farmerId: 'f5',
    farmerName: 'Farmer Rajeev',
    stock: 50,
    isOrganic: true
  }
];
